name: terrafort-lint
on: 
    pull_request_target:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:

        - name: Install Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.7.0"

        - name: Checkout Code
          uses: actions/checkout@main
          with:
            ref: ${{ github.ref }}

        - name: Check terraform formatting
          run: terraform fmt check --recursive